# Data parameters
data:
    dataset: mnist
    data_dir: data/mnist-data
    input_size: [28,28]
    input_channels: 1
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: exps/mnist/test-confidnet_500ep/
    task: classification
    learner: selfconfid
    nb_epochs: 500
    eval_every: 10
    batch_size: 128
    loss:
        name: selfconfid_mse
        weighting: 1
    optimizer:
        name: adam
        lr: 0.0001
    lr_schedule:
    ft_on_val: False
    smoother: 0.1
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: True
    num_workers: 3
    augmentations:
        normalize: [[0.1307,], [0.3081,]]


# Model parameters
model:
    name: mlp_selfconfid
    resume: exps/mnist/test/model_epoch_100.ckpt
    uncertainty:
    hidden_size: 1000
    is_dropout: True